name: notificationsmetodologyservice
services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    restart: always
  dynamodbui:
    container_name: dynamodbui
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      dynamodb:
        condition: service_started